backend:
  name: git-gateway
  accept_roles:
    - admin

public_folder: '/assets'
media_folder: '.vuepress/public/assets'
display_url: https://nonfungible.team/

collections:
  - name: 'pages'
    label: 'Pages'
    delete: false
    description: 'Individual site pages not part of a collection'
    files:
      - label: 'Home'
        name: 'home'
        file: 'README.md'
        description: 'Site home page with paralax landing image'
        fields:
          - {
              label: 'Title',
              name: 'title',
              widget: 'string',
              hint: 'Title used for browser tab title',
            }
          - {
              label: 'Parallax Image',
              name: 'parallaxImage',
              widget: 'file',
              hint: 'Landing Image with paralax effect',
            }
          - {
              label: 'Parallax Header',
              name: 'parallaxHeader',
              widget: 'string',
              hint: 'Main heading centered on paralax area',
            }
          - {
              label: 'Parallax Content',
              name: 'parallaxContent',
              widget: 'text',
              hint: 'Text block centered on paralax area',
            }
      - label: 'Contact'
        name: 'contact'
        file: 'contact.md'
        description: 'A contact page with a contact form'
        fields:
          - {
              label: 'Title',
              name: 'title',
              widget: 'string',
              hint: 'Title used for page heading and browser tab title',
            }
          - {
              label: 'Email',
              name: 'email',
              widget: 'string',
              hint: 'A email for people to contact you at',
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'sample'
    label: 'Samples'
    folder: 'sample'
    delete: false
    description: 'This collection has example markdown content as well as Netlify CMS configuration documentation'
    slug: '{{slug}}'
    fields:
      - {
          label: 'Title',
          name: 'title',
          widget: 'string',
          hint: 'Title used for page heading and browser tab title',
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
